### ISSUE TITLE
Upgrade to Highlight.js v10

### ISSUE THREAD

**Issue by joshgoebel** [felixfbecker/cli-highlight#100]
Highlight.js v9 is very, very old and v10 contains 100s of fixes and improvements.  We also just officially entirely dropped support for v9 and it should now be treated as a potential security risk for anyone still using it.  Your simple uses case makes me think it'd be pretty easy for you to upgrade if you decided to do so.

**Comment by jamezrin** [comment]
I wouldn't hold my breath, this package has not been updated for more than a year.

**Comment by joshgoebel** [comment]
Yeah, I was just dropping the note here since this was mentioned by some of the people trying to sort out their secondary dependencies.  Sad though (if this is still generally useful  - I dunno) because it looks like an easy fix but I don't have time to patch and maintain every single library downstream of us. :-)  But I can ask.

**Comment by joshgoebel** [comment]
If you (or anyone) might want to help I wrote a TINY guide:

https://github.com/highlightjs/highlight.js/issues/2882

**Comment by jamezrin** [comment]
It looks like @felixfbecker is still active in this repo, look at this: https://github.com/felixfbecker/cli-highlight/pull/99#pullrequestreview-532792661

**Comment by felixfbecker** [comment]
Fixed by https://github.com/felixfbecker/cli-highlight/pull/89.

**Comment by felixfbecker** [comment]
And @jamezrin, please spread negativity elsewhere. A package doesn't need updates if it works fine. Stability is a feature, not a bug.
