### ISSUE TITLE
Upgrade to Highlight.js v10.4.1 (or higher)

### ISSUE THREAD

**Issue by corydozen** [felixfbecker/cli-highlight#123]
I have a repo that transitively depends on cli-highlight. I received a dependabot security alert, requesting that highlight.js be upgraded to v10.4.1 or higher. It linked to [this article](https://owasp.org/www-community/attacks/Regular_expression_Denial_of_Service_-_ReDoS).
@joshgoebel do you have any insight?

**Comment by joshgoebel** [comment]
I believe this is covered fully in https://github.com/highlightjs/highlight.js/security/advisories/GHSA-7wwv-vh3v-89cq.   There is no reason anyone on the v10 series already shouldn't upgrade ASAP.

If you have more specific questions I'd be happy to help.

**Comment by joshgoebel** [comment]
Hard to say if your own repo is at risk, would depend how/if you actually use cli-highlight... (see the advisory)

**Comment by felixfbecker** [comment]
We depend on highlight.js `^10`, so `10.4.1` is within range and will be picked by default on new installs. Existing consumers can easily upgrade to `10.4.1` using `npm upgrade`/`yarn upgrade` (same way they would have to upgrade to a new version of `cli-highlight`).

**Comment by joshgoebel** [comment]
@felixfbecker I may not be as well versed in npm stuff as you are. 

Is there any point in bumping your `package.json.lock` file (which references an older insecure version), or does that only really apply to developers working directly on the `cli-highlight` project itself?

**Comment by felixfbecker** [comment]
Yes, bumping the package-lock.json version will upgrade you to the newer version. `npm upgrade` should do this to my knowledge.

**Comment by corydozen** [comment]
My mistake. There's no need to bump the version on this package. It can be `upgrade`d downstream. Thanks for the conversation.
