### ISSUE TITLE
[Question] Text in clipboard > Highlight > Put back in clipboard

### ISSUE THREAD

**Issue by martinandersen3d** [felixfbecker/cli-highlight#145]
Hi, I want to have clear text, from the clipboard, to be Highlighted and be put back in the clipboard as Highlighted text, that can be pasted into Word/Google-docs-programs.

Can this cli do something like this? or is the purpose, to much in another direction?

**Comment by martinandersen3d** [comment]
spell

**Comment by felixfbecker** [comment]
Yeah, it should be pretty easy to read the clipboard on the terminal, pipe it to the CLI, then pipe it into the clipboard again. E.g. on macOS:
```sh
pbpaste | highlight | pbcopy
```
You can control the programming language with `--language`.

**Comment by martinandersen3d** [comment]
thanks :D
