### ISSUE TITLE
XML/HTML support

### ISSUE THREAD

**Issue by gitgrimbo** [felixfbecker/cli-highlight#3]
When trying to highlight an XML file, the `hljs` HTML tags are output.  Is this expected behaviour?  Using the `--language XML` option does not change the output.

Command:

`>highlight pom.xml`

Result:

```
<span class="hljs-tag"><project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"></span>
        <span class="hljs-tag"><modelVersion></span>4.0.0<span class="hljs-tag"></modelVersion></span>
        <span class="hljs-tag"><parent></span>
                <span class="hljs-tag"><groupId></span>org.springframework.boot<span class="hljs-tag"></groupId></span>
                <span class="hljs-tag"><artifactId></span>spring-boot-starter-parent<span class="hljs-tag"></artifactId></span>
                <span class="hljs-tag"><version></span>1.5.2.RELEASE<span class="hljs-tag"></version></span>
        <span class="hljs-tag"></parent></span>
```

![cli-highlight-3](https://cloud.githubusercontent.com/assets/1020541/24966291/6e0fbb2a-1f9e-11e7-834a-2c8516a87585.png)

**Comment by felixfbecker** [comment]
I currently parse the HTML with a regexp, that only works for languages like SQL and JSON. XML and HTML have nested tags. See #1 

It's not hard to do, there are countless HTML parsers on npm, I was just too lazy to implement it because I only needed SQL. Feel free to do a PR :)

**Comment by acarl005** [comment]
Check out my PR #5. It's not the best for performance, but it seems to work for me!
