### ISSUE TITLE
piping into less -r

### ISSUE THREAD

**Issue by aleclarson** [felixfbecker/cli-highlight#31]
```sh
curl -s https://jsonplaceholder.typicode.com/posts | highlight -l json | less -r
```

The syntax colors are not preserved when piping into `less -r`.

**Comment by felixfbecker** [comment]
Wouldn't that be a problem with less, not with cli-highlight?

**Comment by aleclarson** [comment]
No, `less -r` prevents that.

**Comment by felixfbecker** [comment]
Could you try adding `--color` or setting `FORCE_COLOR=1`?

**Comment by aleclarson** [comment]
`--color` works!

Thank you. 😃
