### ISSUE TITLE
esc[39m could be replaced with esc[0m for easier interpretation by other programs?

### ISSUE THREAD

**Issue by christopherreay** [felixfbecker/cli-highlight#35]
if you convert the esc[39m to esc[0m then the output is much easier for other programs to interpret

I have to do this to use ansi2html.sh to create web versions of log output

Thanks for the tool

**Comment by felixfbecker** [comment]
Frankly I don't know what those escape sequences mean, I just use https://github.com/chalk/chalk

**Comment by christopherreay** [comment]
so, the issue is that when "your code" is returning to "default text", there are two ways of doing it

^[39m is "white"
^[0m is "default"

I suppose you have asked chalk to "go to white". I tried to have a look myself, but i couldnt see where the logic for the code was. I can have a look if you like, if you can point me in roughly the right direction

**Comment by felixfbecker** [comment]
The nodes are wrapped in escape sequences here: https://github.com/felixfbecker/cli-highlight/blob/c0751120bf5533b2df52f9938d495ad90183ebee/src/index.ts#L17
with the default theme being defined here: https://github.com/felixfbecker/cli-highlight/blob/c0751120bf5533b2df52f9938d495ad90183ebee/src/theme.ts#L294

**Comment by christopherreay** [comment]
ok, Ill have a look. 

At the moment im processing the output with sed to do the same.

Thanks :)

Christopher

**Comment by sindresorhus** [comment]
> ^[39m is "white"

This is not correct. That escape closes/resets a foreground color.

See: https://github.com/chalk/ansi-styles/blob/de7527a86c1cf49906b0eb32a0de1402d849ccc2/index.js#L34-L51

**Comment by christopherreay** [comment]
ok, so I spoke to chalk, they explained what [39m and [0m mean:

[39m means "reset the foreground color to default"
[0m means "reset everything to default"

So they reckon that it is the script I am using that is bugged, not the output of cli-highlight that should be changed :)

Cheers :)
