### ISSUE TITLE
cli-highlight errors out with certain inputs even though `ignoreIllegals` is set to true

### ISSUE THREAD

**Issue by rsimha** [felixfbecker/cli-highlight#53]
Hi @felixfbecker, we at the AMP Project ([github.com/ampproject/amphtml](https://github.com/ampproject/amphtml)) have been using `cli-highlight` to highlight compiler errors seen while building the AMP runtime. We've found the highlighter to be very useful while presenting errors to developers.

Today, we came across a case where the highlighter errors out for certain input strings even though `ignoreIllegals` was set to true. 

```
Error: Illegal lexeme ":" for mode "<unnamed>"
```

Here is the input string: https://gist.github.com/rsimha/801894e377fd1960dbb184367fe44469

Is this expected? If not, is there something we could do to mitigate the problem?

**Comment by felixfbecker** [comment]
Could you post a full stack trace?

**Comment by rsimha** [comment]
I just checked with @choumx who reported this problem, and it turns out that `cli-highlight` hangs for several seconds without returning a stack trace. The error text pasted above was seen when an exception breakpoint was added.

**Comment by rsimha** [comment]
Will do. Thanks for the prompt help, @felixfbecker!
